"""Our exhaustive KQK/KRK mate-distance tables, generated by original code.

This is permitted endgame tablebase data, not an external engine's answers.
Generation and exhaustive verification scripts remain in the project lab.
Only three-piece positions are served here; the main engine handles all others.
"""
from pathlib import Path
import hashlib
import numpy as np
import chess

_PATH = Path(__file__).with_name('three_piece_dtm.npz')
_TABLES = {}
if _PATH.is_file():
    if hashlib.sha256(_PATH.read_bytes()).hexdigest() != '8a5d9742eed9c7e40b2001b5b37d30c22513d54659da69d4e93caa088e77014f':
        raise RuntimeError('Three-piece table identity mismatch')
    with np.load(_PATH, allow_pickle=False) as data:
        for kind, name in ((chess.QUEEN, 'queen'), (chess.ROOK, 'rook')):
            arr=data[name].copy()
            if arr.shape != (524288,) or arr.dtype != np.uint8:
                raise RuntimeError('Three-piece table shape mismatch')
            arr.flags.writeable=False
            _TABLES[kind]=arr

def distance(board, attacker, kind):
    major=board.pieces(kind,attacker)
    if len(major)!=1:return None
    ak=board.king(attacker);dk=board.king(not attacker)
    if ak is None or dk is None:return None
    idx=int(board.turn!=attacker)*262144+ak*4096+next(iter(major))*64+dk
    value=int(_TABLES[kind][idx])
    return None if value==255 else value

def _choose_original_dtm(board, seen=None):
    if not _TABLES or board.occupied.bit_count()!=3 or board.castling_rights or board.ep_square is not None:
        return None
    major=board.occupied & ~board.kings
    if major.bit_count()!=1:return None
    square=chess.lsb(major);kind=board.piece_type_at(square)
    if kind not in _TABLES:return None
    attacker=board.color_at(square);mover=board.turn
    best=None;best_rank=None
    for move in sorted(board.legal_moves,key=lambda m:m.uci()):
        board.push(move)
        try:
            if board.is_checkmate():
                rank=(1 if mover==attacker else -1,0)
            else:
                d=distance(board,attacker,kind)
                limit=min(100-board.halfmove_clock,600-board.ply())
                repeated=bool(seen and seen.get(board._transposition_key(),0)>=2)
                won=d is not None and d<=limit and not repeated and not board.is_stalemate()
                if won:rank=(1 if mover==attacker else -1,-d if mover==attacker else d)
                else:rank=(0,-(d if d is not None else 255) if mover==attacker else (d if d is not None else 255))
            if best_rank is None or rank>best_rank:best_rank=rank;best=move.uci()
        finally:board.pop()
    return best


# Preserve our original mate-distance policy where it already has coverage.
from syzygy_root import choose_syzygy

def choose_exact(board, seen=None):
    original = _choose_original_dtm(board, seen)
    return original if original is not None else choose_syzygy(board, seen)
